// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfUO5GLACBcRqnWDzKI3ghhJs82A4Yovk',
    appId: '1:618180449324:web:fc62f72ea197a3031d2d89',
    messagingSenderId: '618180449324',
    projectId: 'movieshub-904e1',
    authDomain: 'movieshub-904e1.firebaseapp.com',
    storageBucket: 'movieshub-904e1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7ZaKG23BewFDG4LhipluNKsDyFsdiZYs',
    appId: '1:618180449324:android:0185ceb2057715451d2d89',
    messagingSenderId: '618180449324',
    projectId: 'movieshub-904e1',
    storageBucket: 'movieshub-904e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMQFL2YQJilsegZv_y1tYXQzPVG8LLn6g',
    appId: '1:618180449324:ios:7787c1a1e67c09701d2d89',
    messagingSenderId: '618180449324',
    projectId: 'movieshub-904e1',
    storageBucket: 'movieshub-904e1.firebasestorage.app',
    iosBundleId: 'com.example.stackDesign',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMQFL2YQJilsegZv_y1tYXQzPVG8LLn6g',
    appId: '1:618180449324:ios:7787c1a1e67c09701d2d89',
    messagingSenderId: '618180449324',
    projectId: 'movieshub-904e1',
    storageBucket: 'movieshub-904e1.firebasestorage.app',
    iosBundleId: 'com.example.stackDesign',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfUO5GLACBcRqnWDzKI3ghhJs82A4Yovk',
    appId: '1:618180449324:web:9bea1c893906d5c41d2d89',
    messagingSenderId: '618180449324',
    projectId: 'movieshub-904e1',
    authDomain: 'movieshub-904e1.firebaseapp.com',
    storageBucket: 'movieshub-904e1.firebasestorage.app',
  );
}
